name: ABI Go Bindings Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  GO_VERSION: "1.20.10"

jobs:
  abi_binding:
    name: abi_binding
    runs-on: ubuntu-20.04

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout Teleporter repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Generate ABI Go bindings
        run: |
          export GOPATH=$HOME/go
          export PATH="$PATH:$GOPATH/bin"
          ./scripts/abi_bindings.sh

      - name: Print diff
        run: git --no-pager diff -- abi-bindings/**.go

      - name: Fail if diff exists
        run: git --no-pager diff --quiet -- abi-bindings/**.go

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-20.04

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout repositories and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run ABI Binding Unit Tests
        run: |
          source scripts/constants.sh
          cd abi-bindings/go
          go test ./...
