name: Snyk Golang
on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
    branches:
      - "dependabot/**"
jobs:
  golang-snyk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout subnet-evm
        uses: actions/checkout@v4
        with:
          repository: ava-labs/subnet-evm
          path: subnet-evm

      - name: Run Snyk
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --all-projects --detection-depth=4

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
